version: '3.6'
services:
  frontend:
    build:
      context: ./src/front
      dockerfile: Dockerfile.local
  gateway:
    build:
      context: ./src/gateway
      dockerfile: ./Gateway.Api.Dockerfile
  identity:
    build:
      context: ./src/identity
      dockerfile: ./Identity.Api.Dockerfile
      args:
        FEED_USERNAME: $FEED_USERNAME
        PERSONAL_ACCESS_TOKEN: $PERSONAL_ACCESS_TOKEN
  identity-db-updater:
    build:
      context: ./src/identity
      dockerfile: ./Identity.Database.Dockerfile
  rentals:
    build:
      context: ./src/rentals
      dockerfile: ./Dockerfile
  books:
    build:
      context: ./src/books
      dockerfile: ./Dockerfile
  books-db-updater:
    build:
      context: ./src/books
      dockerfile: ./Books.Database.Dockerfile