version: '3.6'
services:
  react-frontend:
    build:
      context: ./src/react-front
      dockerfile: Dockerfile
    environment:
      - API_URL=http://localhost:8080
  gateway:
    build:
      context: ./src/gateway
      dockerfile: ./Gateway.Api.Dockerfile
  identity:
    build:
      context: ./src/identity
      dockerfile: ./Identity.Api.Dockerfile
  identity-db-updater:
    build:
      context: ./src/identity
      dockerfile: ./Identity.Database.Dockerfile
  rentals:
    build:
      context: ./src/rentals
      dockerfile: ./Dockerfile
  books:
    build:
      context: ./src/books
      dockerfile: ./Dockerfile
  books-db-updater:
    build:
      context: ./src/books
      dockerfile: ./Books.Database.Dockerfile
  movies:
    build:
      context: ./src/movies
      dockerfile: ./Dockerfile
  movies-db-updater:
    build:
      context: ./src/movies
      dockerfile: ./Movies.Database.Dockerfile
