version: '3.6'

networks:
    identity-network:
        name: identity-network
    rentals-network:
        name: rentals-network
    books-network:
        name: books-network

services:
  rabbitmq:
    image: rabbitmq:management
    networks:
      - rentals-network
      - books-network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 60s
      retries: 10
  gateway:
    image: elibraryoncontainers/gateway:$GATEWAY_API_VERSION
    networks:
      - identity-network
      - rentals-network
      - books-network
    depends_on:
      - identity
      - rentals
      - books
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      AuthOptions__Key: $JWT_SECRET
  identity:
    image: elibraryoncontainers/identity:$IDENTITY_API_VERSION
    environment:
      AuthOptions__Key: $JWT_SECRET
      AuthOptions__ExpiredInMinutes: 30
      ConnectionStrings__DefaultConnection: $IDENTITY_CONNECTION_STRING
      ASPNETCORE_ENVIRONMENT: $IDENTITY_API_ENVIRONMENT
    networks:
      - identity-network
  identity-db-updater:
    image: elibraryoncontainers/identity-db-updater:$IDENTITY_DB_UPDATER_VERSION
    environment:
      Database_ConnectionString: $IDENTITY_UPDATER_CONNECTION_STRING
    networks:
      - identity-network
  rentals:
    image: elibraryoncontainers/rentals:$RENTALS_API_VERSION
    environment:
      RABBITMQ_PORT: $RABBIT_PORT
      RABBITMQ_HOST: $RABBIT_HOST
      DB_URL: $RENTALS_CONNECTION_STRING_NO_AUTH
      DB_USERNAME: $RENTALS_USER
      DB_PASSWORD: $RENTALS_PASSWORD
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - rentals-network
  books:
    image: elibraryoncontainers/books:$BOOKS_API_VERSION
    environment:
      ConnectionStrings__DapperConnection: $BOOKS_CONNECTION_STRING
      RabbitMq__HostName: $RABBIT_HOST
    depends_on:
      rabbitmq:
        condition: service_healthy
      rentals:
        condition: service_started
    networks:
      - books-network
  books-db-updater:
    image: elibraryoncontainers/books-db-updater:$BOOKS_DB_UPDATER_VERSION
    environment:
      Database_ConnectionString: $BOOKS_UPDATER_CONNECTION_STRING
    networks:
      - books-network