spring:
  rabbitmq:
    username: "guest"
    password: "guest"
    port: 5672
  datasource:
    url: jdbc:postgresql://localhost:5432/rentals
    username: rentals
    password: rentals
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/master.xml

rabbitmq:
  topic-exchange:
    name: "rentals"
  rent-queue:
    name: "rent"
  return-queue:
    name: "return"
  extend-queue:
    name: "extend"

logging:
  file:
    name: logs/RentalService.log

  pattern:
    file:
      "[%d{yyyy-MM-dd HH:mm:ss.SSS}] [LEVEL: %-5level] [CLASS: %-40logger{39}] %msg%n"

  level:
    root: info

  logback:
    rollingpolicy:
      max-history: 2
      max-file-size: 20MB
