spring:
  rabbitmq:
    username: "guest"
    password: "guest"
    port: 5672
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true

rabbitmq:
  topic-exchange:
    name: "rentals"
  rent-queue:
    name: "rent"
  return-queue:
    name: "return"
  extend-queue:
    name: "extend"

logging:
  file:
    name: logs/RentalService.log

  pattern:
    file:
      "[%d{yyyy-MM-dd HH:mm:ss.SSS}] [LEVEL: %-5level] [CLASS: %-40logger{39}] %msg%n"

  level:
    root: info

  logback:
    rollingpolicy:
      max-history: 2
      max-file-size: 20MB
