CREATE TABLE Audiobooks (
    Id INT GENERATED ALWAYS AS IDENTITY,
    BookId INT,
    InPreview BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY	(Id),
    FOREIGN KEY (BookId) REFERENCES Books(BookId)
);

CREATE TABLE People (
    Id INT GENERATED ALWAYS AS IDENTITY,
    Surname VARCHAR(255),
    Name VARCHAR(255),
    PRIMARY KEY	(Id)
);