@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!include <logos/rabbitmq.puml>

!include DEVICONS/dotnet.puml
!include DEVICONS/postgresql.puml

LAYOUT_WITH_LEGEND()

title Component diagram for eLibraryOnContainers - Rental service

Container(gateway, "API Gateway", ".NET with ASP.NET Core", "Routes all requests to appropriate services endpoints", $sprite="dotnet")
ContainerQueue(rabbit, "Event bus", "RabbitMQ", "Event bus for asynchronous communication", $sprite=rabbitmq)
ContainerDb(rentals_db, "Rentals database", "PostgreSQL", "Holds rentals events and physical copies information", $sprite="postgresql")
ContainerDb(rentals_read_db, "Rentals (READ) database", "PostgreSQL", "Holds aggregated rentals and physical copies availability information", $sprite="postgresql")

Container_Boundary(rentals, "Rental service") {
  Component(rentalController, "Rentals Controller", "Rest Controller", "Allows users to send requests related to book renting.")

  Component(rentalReader, "Rentals Reader", "Spring service", "Reads projection from READ database.")
  Component(rentalWorker, "Rentals Worker", "Events consumer", "Consumes rentals events.")
  Component(rentalService, "Rentals Service", "Events publisher", "Produces rentals events.")

  Component(rentalRepository, "Rentals Repository", "Spring repository", "Provides functionality related to database operations like reading and updating projection in READ database")
  Component(rentalEventRepository, "Rentals Event Repository", "Spring repository", "Provides functionality related to write-only event database operations like writing and aggregating events to database")
}

Rel(gateway, rentalController, "Uses", "JSON/HTTPS")

Rel(rentalController, rentalReader, "Uses")
Rel(rentalController, rentalService, "Uses")

Rel(rentalWorker, rentalRepository, "Uses")
Rel(rentalWorker, rabbit, "Consumes events", "async, JSON/HTTPS")

Rel(rentalReader, rentalRepository, "Uses")
Rel(rentalRepository, rentals_read_db, "Reads from and writes to", "async, JDBC")

Rel(rentalService, rabbit, "Publishes events", "async, JSON/HTTPS")
Rel(rentalService, rentalEventRepository, "Uses")

Rel(rentalEventRepository, rentals_db, "Writes to", "async, JDBC")
@enduml
