name: 'Set project environment variables for workflows'
description: 'Configures environment variables for a workflow'
runs:
  using: "composite"
  steps:
    - run: |
        cat .github/vars/* >> $GITHUB_ENV
      shell: bash