name: Build docs

on:
  pull_request:
    branches:
      - develop
    paths:
      - src/**
      - docs/**
      - c4builder/**
      - .github/workflows/build-docs.yml
      - .github/workflows/publish-docs.yml
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set environment variables
      uses: ./.github/actions/set-env

    - name: Setup .NET ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: latest

    - name: Build C4-Builder diagrams page
      working-directory: c4builder
      run: |
        npm i -g c4builder
        c4builder
     
    - name: Process diagrams markdown file
      run: |
        sed -E -i '/\*[ ]\[Top\]\(\#Top\)/d' c4builder/docs/eLibraryOnContainers.md
        sed -E -i '/\#\# Top/d' c4builder/docs/eLibraryOnContainers.md
        sed -E -i 's/\s{2}([ ]*)\* \[\S\s(.*)\]\(\#\S-(.*)\)/\1\* \[\2\]\(\#\L\3\)/' c4builder/docs/eLibraryOnContainers.md
        sed -E -i '/\[Top\]\(\#eLibraryOnContainers\)/d' c4builder/docs/eLibraryOnContainers.md
        sed -E -i 's/\#\#\s\S\s(.*)/## \1/' c4builder/docs/eLibraryOnContainers.md
          
    - name: Copy diagrams to DocFx
      run: |
        cp c4builder/docs/eLibraryOnContainers.md docs/articles/diagrams.md
        
    - name: Build documentation
      uses: nikeee/docfx-action@v1.0.0
      with:
        args: docs/docfx.json
      continue-on-error: false
      
    - name: Cache docs
      uses: actions/cache@v3
      with:
        path: docs/_site
        key: docs-${{ github.run_id }}
        restore-keys: docs-