name: FunctionalValidation-PublishPackage

on:
  pull_request:
    branches: 
      - develop
    paths:
      - '.github/workflows/functional-validation-publish.yml'
      - 'src/shared/FunctionalValidation/**'
    # types: [closed]

     
jobs:
  publish:
    # if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set environment variables
        uses: ./.github/actions/set-env
        
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name: Restore dependencies
        run: dotnet restore src/shared/FunctionalValidation
        
      - name: Test
        run: dotnet test -c Release --no-build --verbosity normal src/shared/FunctionalValidation.Tests
          
      - name: Get current date for version
        uses: josStorer/get-current-time@v2.0.2
        id: current-time
        with:
          format: YYYY.MM.DD
          
      - name: Create library version
        run: |
          echo "VERSION=$(echo ${{ steps.current-time.outputs.formattedTime }}.${{ github.run_number }})" >> $GITHUB_ENV
          
      - name: Build
        run: dotnet build -c Release --no-restore -p:Version=$VERSION src/shared/FunctionalValidation
          
      - name: Create commit tag with library version
        run: |
          git tag FunctionalValidation-${{ env.VERSION }}
          git push origin FunctionalValidation-${{ env.VERSION }}
          
      - name: Build and Pack NuGet package
        run: dotnet pack src/shared/FunctionalValidation/FunctionalValidation.csproj -p:Version='${{ env.VERSION }}' -c Release
        
      - name: Publish
        run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
      