name: Publish docs on GitHub Pages

on:
  push:
    branches:
      - develop
    paths:
      - src/**
      - docs/**
      - c4builder/**
      - .github/workflows/build-docs.yml
      - .github/workflows/publish-docs.yml

jobs:
  build:
    uses: ./.github/workflows/build-docs.yml
    
  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Restore docs from cache
      uses: actions/cache@v3
      with:
        path: docs/_site
        key: docs-${{ github.run_id }}
    
    - name: Publish
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_site
        force_orphan: true