name: Rentals-Tests

on:
  pull_request:
    paths:
      - '.github/workflows/rentals-test.yml'
      - 'src/rentals/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run build with Gradle Wrapper
        run: cd src/rentals && ./gradlew build